dist: xenial

addons:
  postgresql: 9.6

services:
  - postgresql

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip


env:
  global:
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/flask-taxonomies-test"
  matrix:
    - REQUIREMENTS=release EXTRAS=postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release EXTRAS=sqlite,tests

python:
  - "3.7"
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools"
  - "travis_retry pip install twine wheel coveralls pip-tools"

install:
  - "travis_retry pip install -e .[$EXTRAS]"

before_script:
  - psql -U postgres -c "create database flask-taxonomies-test"
  - psql -U postgres -c "create extension ltree" -d flask-taxonomies-test

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Vr+tU9zuP1fS8g2W7FRIEPz1D4BGoo7MbEu1sICwRw+gXpUu75jwyN2FSZVPS/Snr3gm25BFhvhBtI5GrspXnPV65oqhEUdgkfMHniHAW0/yUEl4Nk7LiQBSqmT812HwkRVST5Q+NkRWe3isETxT2ihHqw0LKdUT9rynkfp8BZbozfPfbIDN3vuPCbB3tYjBpdWSHXplO6AB+AM6ojHW0Vs/dtKIzaIIZ3NuDD6OXhWm5WWlY3LbrpFccSNNo9TRXFLPztsNAKehwjyRP6u2kPToC0TJwZkMMQeaHAwIlrPmdNYPRVQwlDYPCRf0zg4JInX029JW/h0DC+ZYDcoI0fLYmY2VOS2eIl/52hbJRk+dxyy/SMRh1gh7yHWbtDuV+WxRLNZsapARpLTqTEGSVqLjEzwoUlkSAzr0CIbfIU16CrOBkBE4vf/6j2x/Iw9lrjgTwzIq/Q0r6EsRZf1ClGP+Tof6F5/pjp5nhti9R8+AnpUfsokQBSOGLhRkuXz+UjHAnxzYADVNOJ7bbqxOAD3ioRxng0P6r+dl5kNqKdhBmbqTjQUucu1Z90PAvUrcB+K8ZcUPlZyVdbfnKlnNXoY07RBFWWBXnP41b4ekL0IJU+GYSxh9OpZksUta64NA4AeQ3OD+K3FdevqcuGeeKaKwH0tHz0s4qo4bovyBrcM="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
