dist: xenial

addons:
  postgresql: 9.6
  apt:
      packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

services:
  - mysql
  - postgresql

notifications:
  email: false

sudo: required

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - MYSQL_SQLALCHEMY_DATABASE_URI="mysql://root@localhost/invenio"
  matrix:
    - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release EXTRAS=all,sqlite
    - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI=$MYSQL_SQLALCHEMY_DATABASE_URI

python:
  - "3.6"
  - "3.7"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

#deploy:
#  provider: pypi
#  user: TODO: PYPIUSERNAME
#  password:
#    secure: TODO: PYPISECUREHASH
#  distributions: "compile_catalog sdist bdist_wheel"
#  on:
#    tags: true
#    python: "3.6"
#    repo: cis/cis-theses-repository
#    condition: $DEPLOY = true
