# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
- FLASK_APP=ext.py FLASK_DEBUG=1 FLASK_ENV=development DATABASE_URL=sqlite:////tmp/dev.db SECRET_KEY=not-so-secret
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements/dev.txt
before_script:
  - flask lint --check
script: flask test
after_success:
  - coveralls
